create extension if not exists pgcrypto;

create table if not exists public.words (
  id uuid primary key default gen_random_uuid(),
  word text not null,
  word_lc text generated always as (lower(word)) stored,
  created_at timestamptz not null default now()
);

create unique index if not exists words_word_lc_unique on public.words (word_lc);

alter table public.words enable row level security;

drop policy if exists "Public read words" on public.words;
create policy "Public read words" on public.words
  for select
  using (true);

drop policy if exists "Public insert words" on public.words;
create policy "Public insert words" on public.words
  for insert
  with check (char_length(word) between 1 and 64);

alter publication supabase_realtime add table public.words;

insert into public.words (word)
values
  ('abasia'),
  ('abelia'),
  ('abetalipoproteinemia'),
  ('abibliofobia'),
  ('abisinia'),
  ('ablepsia'),
  ('ablutofilia'),
  ('ablutofobia'),
  ('ablutomania'),
  ('abrosia'),
  ('abstinensia'),
  ('abulia'),
  ('acacia'),
  ('acidemia'),
  ('acintia'),
  ('aclisia'),
  ('acronychia'),
  ('actinaria'),
  ('adenia'),
  ('adermatoglifia'),
  ('adikia'),
  ('adimanusia'),
  ('adinamia'),
  ('adipsia'),
  ('adisatria'),
  ('aditia'),
  ('adiwidia'),
  ('adularia'),
  ('adventisia'),
  ('adverbia'),
  ('aerofagia'),
  ('aerofobia'),
  ('aeronausifobia'),
  ('aeroterapia'),
  ('afagia'),
  ('afakia'),
  ('afantasia'),
  ('afasia'),
  ('afemia'),
  ('afenfosmefobia'),
  ('afibrinogenemia'),
  ('afonia'),
  ('afrasia'),
  ('agalaksia'),
  ('ageusia'),
  ('agiria'),
  ('agirofobia'),
  ('aglaia'),
  ('agliofobia'),
  ('agnosia'),
  ('agonia'),
  ('agorafobia'),
  ('agrafestesia'),
  ('agrafia'),
  ('agrafobia'),
  ('agraria'),
  ('agripnia'),
  ('agrizoofobia'),
  ('abesif'),
  ('abrasif'),
  ('abusif'),
  ('adhesif'),
  ('adrif'),
  ('agresif'),
  ('akuif'),
  ('alif'),
  ('anaglif'),
  ('antihipertensif'),
  ('antikorosif'),
  ('antipasif'),
  ('antitusif'),
  ('arif'),
  ('bermuradif'),
  ('bertakrif'),
  ('bertarif'),
  ('brigif'),
  ('daif'),
  ('defensif'),
  ('delusif'),
  ('depresif'),
  ('dif'),
  ('diskursif'),
  ('drif'),
  ('egresif'),
  ('eksesif'),
  ('eksklusif'),
  ('ekskursif'),
  ('ekslusif'),
  ('ekspansif'),
  ('eksplosif'),
  ('ekspresif'),
  ('ekstensif'),
  ('abadiat'),
  ('afiat'),
  ('ahadiat'),
  ('akiat'),
  ('alimiat'),
  ('antikuariat'),
  ('baiat'),
  ('bergeliat'),
  ('bergiat'),
  ('berkhasiat'),
  ('berkiat'),
  ('bermaksiat'),
  ('berniat'),
  ('bersekretariat'),
  ('bertabiat'),
  ('berwasiat'),
  ('biat'),
  ('dahiat'),
  ('diat'),
  ('dibaiat'),
  ('duriat'),
  ('ekspatriat'),
  ('fiat'),
  ('geliat'),
  ('gemiat'),
  ('giat'),
  ('iat'),
  ('ilahiat'),
  ('impresariat'),
  ('intermediat'),
  ('jariat'),
  ('juriat'),
  ('kaifiat'),
  ('kasiat'),
  ('kepiat'),
  ('ablatif'),
  ('abortif'),
  ('absorptif'),
  ('adaptif'),
  ('adiktif'),
  ('aditif'),
  ('adjektif'),
  ('adjudikatif'),
  ('administratif'),
  ('adoptif'),
  ('adsorptif'),
  ('adventif'),
  ('afektif'),
  ('aferitif'),
  ('afirmatif'),
  ('agentif'),
  ('agitatif'),
  ('aglutinatif'),
  ('agregatif'),
  ('ajektif'),
  ('akomodatif'),
  ('akseleratif'),
  ('aktif'),
  ('akumulatif'),
  ('akusatif'),
  ('alatif'),
  ('alteratif'),
  ('alternatif'),
  ('amelioratif'),
  ('antidegeneratif'),
  ('antisipatif'),
  ('adaks'),
  ('afiks'),
  ('afluks'),
  ('agrokompleks'),
  ('aks'),
  ('aloleks'),
  ('ambaks'),
  ('ambifiks'),
  ('anoks'),
  ('antefiks'),
  ('anteliks'),
  ('antiklimaks'),
  ('antraks'),
  ('apendiks'),
  ('berafiks'),
  ('berklimaks'),
  ('berkonfiks'),
  ('berkonteks'),
  ('berkuteks'),
  ('berparadoks'),
  ('berprefiks'),
  ('bersufiks'),
  ('bikonveks'),
  ('biloks'),
  ('birofaks'),
  ('biseks'),
  ('bkkks'),
  ('boks'),
  ('bomseks'),
  ('boraks'),
  ('botoks'),
  ('brafaks'),
  ('cuaks'),
  ('deks'),
  ('detoks'),
  ('difaks')
on conflict (word_lc) do nothing;

